<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>RoflBatchExporter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\lib\roflxd.cs-master\Rofl.Extract.Data\Rofl.Extract.Data.csproj" />
  </ItemGroup>

</Project>
